language: python
python: 2.7
cache:
- pip
directories:
  - $HOME/.cache/pip

env:
  global:
  - TEST_RESILIENT_APPLIANCE=staging2.internal.resilientsystems.com
  - OCTOKIT_API_ENDPOINT="https://github.ibm.com/api/v3/"
  - PIP_FIND_LINKS="$TRAVIS_BUILD_DIR/pkgs"
  - secure: VU1PL2bWOE+E3ieBz/0Oa2hIRXGeSFYubE9SYh3dH541h8V8FWE0kGt8P6xdZOGmf9xNsDL/O+rKqrq5TCKTdUQqFXm7RCD//iQrHUcbu2YU38XPpBQrWxSZs29sR3R6UkUypZahHmn/ghjgZnRxQIWGscYPvvNCiOP9X85ckmVaKLYPwW0HPH7vIKs9zcT8tEyRDANokc0BQDjeVu0s29FeKGyy9JVbuye8/1TmVkQWBvutvcQ/z/mOQ7dOO3fW0wkVwOHPF9FtBc79WzjK5w/Ej30EWHC5zdRG46+2FLcqKSHvkyuV59f0ojxLzRmeR1ueS37pNncmXfVMREwtiIYN/Dd3isLsg14RK1leu/JHiPxfQtz2TV4+yeVO4aZk+Bs/JLf1ZbXAE+A71hIH6rTUpEBq1S8qjKsfTPEWLg1cuq1ujf2WOAumdIf8rSOnQ9EbEfBlm3N8Wo9RjXbEx6hq+UHr7L28tw0u00gcAex6Ky2eRk+USFnXBHs/Kf5i29CWzw4Lcnb2hPa0bup3yNQuss/Yy+cQO5tDW8jJPP8joR5Fvr8fJZVtGlTGp09odHcrDGKvbdlf0gVmVDYawKi0v4m0URCKVy0vYAbzVOgZF46nW+VfcexiLxomwYpKeltigk+L52aV5DIodfuxS9aB6IJtEYSTO8Mf+Yo2x8Q=
  - secure: kr5Zz5frfrGOeuAylefGbDhY5s/YwyRhktuAly1ovOn/7Q3OJYjTq6h7wvnt1KQ/YeSdA+bxwOhWKbYHPQHAhovyo/5gsII7LruSs7VjdcD9tDoaYEoDBP7nki+NGr+dBVwrooGJ3f7TbuZs+4OSyPWD2FdN4PsOYLof4soDEW7C0cTP2KZ/wNGDjBGB2stOb6a5h4MQSohx+7B795noUoK5ojmygZObIGSDWmahR4kzCm+rEVLlMV0ptDCBXvn4xmJLCz5UOZhR27ckuiW342vNxShlms+rwWcvoxwbj61Qn3MEf9S9D59aJ+n4+u9Kb3VD4HJjlQ3rWZ/DADPfp7h6XOmfrQq3Xj3sQ4K2+8RMSFHdxWPsmhWd/Aty+YmWjoOnewoBfFaDUzFRURqwO3K+oh1H0IALTOTYQSYEeuVfi/+mwJRkKh0+IgvgscL5/bo+nVnQBk4FpWJRHV0x2fWiG8DHCKmInkkFSDHax3dHc9pYZXQTdNdfvsJRtc0rEn6GyVnRMia1TKLpB1joRhb7mkyc7pgDSatvV9W6+v6+evplHFxS7lkm9gqlW/ygJzPVYx7UaFuqo9cOi/c8sR6qf7NUTUi9Aa4aqY6qHNrkxfh7+5ck7wLTWmE0WL+0r3Z09Zg746SIGYqLrFQJZPn+JanFEy0q7kAU2Zr8vgE=

stages:
  - run tests for most recently modified integration on push
  - mock-tests
  - live-tests
  # - name: platform tests
  #   if: branch = master AND type=pull_request

matrix:
  fast_finish: true
  include:
  # Jobs below this line are reserved for push contributions i.e when someone pushes changes
  # ==========
  # Below jobs are used to run tests against the most recently modified integration. 
  # We determine the most recent one using ls. 
  - name: run 2.7 tests on most recent modified integration
    stage: run tests for most recently modified integration on push
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch != master AND type=push
    #stage: mock-tests
    python: 2.7
    name: "Python 2.7 Build and Run Tests"
    env:
    - TOXENV=py27 TEST_RESILIENT_ORG="Resilient Integrations - Test"
  - name: run 3.4 tests on most recent modified integration
    stage: run tests for most recently modified integration on push
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch != master AND type=push
    #stage: mock-tests
    python: 3.4
    name: "Python 3.4 Build and Run Tests"
    env:
    - TOXENV=py34 TEST_RESILIENT_ORG="Resilient Integrations - Test" 
    script:
      - echo "3.4 push test" && .scripts/build_most_recent_package.sh && .scripts/run_most_recent_tests.sh 
install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install tox
  - pip install sphinx
  - pip install pytest==4.0.1 # Install 4.0.1 to avoid namespace issue 
  - pip install resilient
  - pip install resilient-circuits
  - pip install resilient-lib
  - pip install pytest-resilient-circuits

# # Before script step to clone and build out the Resilient, Resilient-Circuits and other packages needed.
# before_script:
#   - git clone -b master --single-branch git@github.ibm.com:Resilient/resilient-python-api.git --depth 1
#   - (cd resilient-python-api && ./buildall.sh 999);
#   - mkdir pkgs
#   - cp resilient-python-api/*/dist/*.tar.gz ./pkgs

# Run scripts to build our packages
script:
  - .scripts/build_packages.sh && .scripts/run_tests.sh

after_script:
  - echo "Packages To Deploy"
  - ls -l .scripts/*.tar.gz

after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat

notifications:
  email: false